import type { Metadata } from 'next';
import '../globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function AuthLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div
      className="
          h-full 
          flex 
          items-center 
          justify-center 
          bg-[radial-gradient(ellipse_at_top,_var(--tw-gradient-stops))] 
          from-emerald-400 to-emerald-800"
    >
      {children}
    </div>
  );
}
