import type { Metadata } from 'next';
import { outfit } from './fonts';
import './globals.css';
import { Button } from '@/components/ui/button';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${outfit.variable}`} suppressHydrationWarning={true}>
        {children}
      </body>
    </html>
  );
}
